name: io
description: >
  Utilities for the Dart VM Runtime.
version: 0.2.0
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/io

environment:
  sdk: ">=1.22.0 <2.0.0"

dev_dependencies:
  path: ^1.0.0
  test: ^0.12.0
