name: io
description: >-
  Utilities for the Dart VM Runtime including support for ANSI colors,
  file copying, and standard exit code values.
version: 0.3.5-dev
homepage: https://github.com/dart-lang/io

environment:
  sdk: ">=2.11.99 <3.0.0"

dependencies:
  meta: ^1.0.2
  path: ^1.5.1
  string_scanner: ">=0.1.5 <2.0.0"

dev_dependencies:
  dart_style: ^1.0.7
  pedantic: ^1.2.0
  test: ^1.0.0
  test_descriptor: ^2.0.0
