name: io
description: >
  Utilities for the Dart VM Runtime.
version: 0.2.1
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/io

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  meta: ^1.0.2
  path: ^1.0.0

dev_dependencies:
  dart_style: ^1.0.7
  test: ^0.12.0
